# Generated by Django 5.1.3 on 2024-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
