# Generated by Django 5.1.2 on 2024-12-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_age_category_scenario_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_options', to='game.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('difficult', 'Difficult')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='option',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
